-- Durable content-free outbox. Publishers assign sequence after mutation commit.
CREATE TABLE IF NOT EXISTS federation_change_clock (id INTEGER PRIMARY KEY, value BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS federation_changes (event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, seq BIGINT,memory_id TEXT NOT NULL,changed_at TIMESTAMPTZ NOT NULL,old_namespace TEXT,old_category TEXT,old_public INTEGER NOT NULL,old_exportable INTEGER NOT NULL,new_namespace TEXT,new_category TEXT,new_public INTEGER NOT NULL,new_exportable INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS federation_receive_state (peer_name TEXT NOT NULL,remote_id TEXT NOT NULL,last_sequence BIGINT,remote_updated TIMESTAMPTZ,withdrawn INTEGER NOT NULL,PRIMARY KEY(peer_name,remote_id));
CREATE TABLE IF NOT EXISTS federation_peer_cursors (peer_id TEXT PRIMARY KEY,cursor_value VARCHAR(2048),filter_signature VARCHAR(64));
CREATE INDEX IF NOT EXISTS idx_fed_changes_memory_seq ON federation_changes(memory_id,seq);

INSERT INTO federation_change_clock(id,value) VALUES(1,0) ON CONFLICT(id) DO NOTHING;
CREATE OR REPLACE FUNCTION fed_journal_insert_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF (NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault')) THEN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) VALUES(NEW.id,clock_timestamp(),NULL,NULL,0,0,NEW.namespace,NEW.category,CASE WHEN MOD(NEW.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault') AND NEW.deleted_at IS NULL AND NEW.archived_at IS NULL AND NEW.consolidated_into IS NULL THEN 1 ELSE 0 END);
 END IF;
 RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS fed_journal_insert ON memories;
CREATE TRIGGER fed_journal_insert AFTER INSERT ON memories FOR EACH ROW EXECUTE FUNCTION fed_journal_insert_fn();
CREATE OR REPLACE FUNCTION fed_journal_update_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF ((OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault')) OR (NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault'))) AND (OLD.federation_source::text IS DISTINCT FROM NEW.federation_source::text OR OLD.content::text IS DISTINCT FROM NEW.content::text OR OLD.category::text IS DISTINCT FROM NEW.category::text OR OLD.subcategory::text IS DISTINCT FROM NEW.subcategory::text OR OLD.namespace::text IS DISTINCT FROM NEW.namespace::text OR OLD.owner_id::text IS DISTINCT FROM NEW.owner_id::text OR OLD.permission_mode::text IS DISTINCT FROM NEW.permission_mode::text OR OLD.deleted_at::text IS DISTINCT FROM NEW.deleted_at::text OR OLD.archived_at::text IS DISTINCT FROM NEW.archived_at::text OR OLD.consolidated_into::text IS DISTINCT FROM NEW.consolidated_into::text OR OLD.updated::text IS DISTINCT FROM NEW.updated::text OR OLD.embedding::text IS DISTINCT FROM NEW.embedding::text OR OLD.metadata::text IS DISTINCT FROM NEW.metadata::text OR OLD.verbatim_content::text IS DISTINCT FROM NEW.verbatim_content::text OR OLD.source_model::text IS DISTINCT FROM NEW.source_model::text OR OLD.source_provider::text IS DISTINCT FROM NEW.source_provider::text OR OLD.source_agent::text IS DISTINCT FROM NEW.source_agent::text OR OLD.source_session::text IS DISTINCT FROM NEW.source_session::text) THEN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) VALUES(NEW.id,clock_timestamp(),OLD.namespace,OLD.category,CASE WHEN MOD(OLD.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault') AND OLD.deleted_at IS NULL AND OLD.archived_at IS NULL AND OLD.consolidated_into IS NULL THEN 1 ELSE 0 END,NEW.namespace,NEW.category,CASE WHEN MOD(NEW.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault') AND NEW.deleted_at IS NULL AND NEW.archived_at IS NULL AND NEW.consolidated_into IS NULL THEN 1 ELSE 0 END);
 END IF;
 RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS fed_journal_update ON memories;
CREATE TRIGGER fed_journal_update AFTER UPDATE ON memories FOR EACH ROW EXECUTE FUNCTION fed_journal_update_fn();
CREATE OR REPLACE FUNCTION fed_journal_delete_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF (OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault')) THEN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) VALUES(OLD.id,clock_timestamp(),OLD.namespace,OLD.category,CASE WHEN MOD(OLD.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault') AND OLD.deleted_at IS NULL AND OLD.archived_at IS NULL AND OLD.consolidated_into IS NULL THEN 1 ELSE 0 END,NULL,NULL,0,0);
 END IF;
 RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS fed_journal_delete ON memories;
CREATE TRIGGER fed_journal_delete AFTER DELETE ON memories FOR EACH ROW EXECUTE FUNCTION fed_journal_delete_fn();
BEGIN;
INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT m.id,clock_timestamp(),NULL,NULL,0,0,m.namespace,m.category,CASE WHEN MOD(m.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault') AND m.deleted_at IS NULL AND m.archived_at IS NULL AND m.consolidated_into IS NULL THEN 1 ELSE 0 END FROM memories m WHERE (m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault')) AND NOT EXISTS(SELECT 1 FROM federation_changes e WHERE e.memory_id=m.id);
COMMIT;
CREATE INDEX IF NOT EXISTS idx_fed_changes_pending ON federation_changes(seq,event_id);
