-- 0002b_graeae.sql — GRAEAE consultation + audit-log tables for Db2 12.1.5.
-- Ports db/migrations_oracle/0002_graeae.sql to Db2-compat (cross-backend parity):
--   VARCHAR2->VARCHAR; NUMBER->INTEGER/DECIMAL; SYSTIMESTAMP->CURRENT_TIMESTAMP;
--   drop ``CHECK (col IS JSON)`` (unsupported on the EAP — keep CLOB);
--   inline-PK columns carry explicit NOT NULL (Oracle-compat does not auto-promote).
-- Needed by Db2ConsultationsRepository.create_consultation_with_audit (the GRAEAE
-- hash-chained consultation write). memory_id matches db2 memories.id VARCHAR(100).

CREATE TABLE graeae_consultations (
  id                       VARCHAR(36)              NOT NULL PRIMARY KEY,
  prompt                   CLOB(2M)                 NOT NULL,
  task_type                VARCHAR(100),
  context_uncompressed     CLOB(2M),
  context_compressed       CLOB(2M),
  context_quality_rating   INTEGER,
  context_quality_summary  CLOB(1M),
  compression_manifest     CLOB(1M),
  context_memory_ids       CLOB(1M),
  consensus_response       CLOB(2M)                 NOT NULL,
  consensus_score          DECIMAL(10, 4),
  winning_muse             VARCHAR(100),
  cost                     DECIMAL(18, 6),
  latency_ms               INTEGER,
  "mode"                   VARCHAR(50),
  created                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  model_variants           CLOB(1M),
  CONSTRAINT valid_quality CHECK (context_quality_rating IS NULL OR (context_quality_rating >= 0 AND context_quality_rating <= 100)),
  CONSTRAINT valid_consensus_score CHECK (consensus_score IS NULL OR (consensus_score >= 0 AND consensus_score <= 1.0))
);

CREATE TABLE graeae_audit_log (
  id               VARCHAR(36)              NOT NULL PRIMARY KEY,
  sequence_num     BIGINT                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  consultation_id  VARCHAR(36),
  prompt           CLOB(2M)                 NOT NULL,
  prompt_hash      VARCHAR(64),
  provider         VARCHAR(50)              NOT NULL,
  model            VARCHAR(100),
  response_text    CLOB(2M),
  response_hash    VARCHAR(64)              NOT NULL,
  chain_hash       VARCHAR(64)              NOT NULL,
  prev_id          VARCHAR(36),
  prev_chain_hash  VARCHAR(64),
  task_type        VARCHAR(100),
  quality_score    DECIMAL(10, 4),
  latency_ms       INTEGER,
  cost_usd         DECIMAL(18, 6),
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_graeae_audit_seq UNIQUE (sequence_num),
  CONSTRAINT fk_audit_log_consultation FOREIGN KEY (consultation_id) REFERENCES graeae_consultations(id) ON DELETE CASCADE,
  CONSTRAINT valid_chain_hash CHECK (LENGTH(chain_hash) = 64),
  CONSTRAINT valid_response_hash CHECK (LENGTH(response_hash) = 64)
);

CREATE INDEX idx_graeae_audit_log_consultation ON graeae_audit_log (consultation_id);

CREATE INDEX idx_graeae_audit_log_created_at ON graeae_audit_log (created_at DESC);

CREATE INDEX idx_graeae_audit_log_chain_hash ON graeae_audit_log (chain_hash);

CREATE TABLE consultation_memory_refs (
  id               VARCHAR(36)              NOT NULL PRIMARY KEY,
  consultation_id  VARCHAR(36)              NOT NULL,
  memory_id        VARCHAR(100),
  relevance_score  DECIMAL(10, 4),
  injected_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cmr_consultation FOREIGN KEY (consultation_id) REFERENCES graeae_consultations(id) ON DELETE CASCADE,
  CONSTRAINT fk_cmr_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE SET NULL
);

-- DB2 forbids a nullable column in a UNIQUE CONSTRAINT (memory_id is nullable via
-- ON DELETE SET NULL); use a UNIQUE INDEX with EXCLUDE NULL KEYS instead, which
-- allows multiple NULL-memory_id rows while enforcing uniqueness on real refs.
CREATE UNIQUE INDEX unique_consultation_memory
  ON consultation_memory_refs (consultation_id, memory_id) EXCLUDE NULL KEYS;

CREATE INDEX idx_cmr_consultation ON consultation_memory_refs (consultation_id);

CREATE INDEX idx_cmr_memory ON consultation_memory_refs (memory_id);

CREATE INDEX idx_cmr_injected_at ON consultation_memory_refs (injected_at DESC);
