-- 0002_graeae.sql — Db2 parity backfill for GRAEAE tables.
-- Statement terminator: @

BEGIN NOT ATOMIC
  IF NOT EXISTS (SELECT 1 FROM SYSCAT.TABLES WHERE TABSCHEMA = CURRENT SCHEMA AND TABNAME = 'GRAEAE_CONSULTATIONS') THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE graeae_consultations (
        id VARCHAR(36) NOT NULL PRIMARY KEY,
        prompt CLOB NOT NULL,
        task_type VARCHAR(100),
        context_uncompressed CLOB,
        context_compressed CLOB,
        context_quality_rating DOUBLE,
        context_quality_summary CLOB(1M),
        compression_manifest CLOB(1M),
        context_memory_ids CLOB(1M),
        consensus_response CLOB NOT NULL,
        consensus_score DOUBLE,
        winning_muse VARCHAR(100),
        cost DOUBLE,
        latency_ms INTEGER,
        mode VARCHAR(50),
        created TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        model_variants CLOB(1M)
      )';
  END IF;
END@

BEGIN NOT ATOMIC
  IF NOT EXISTS (SELECT 1 FROM SYSCAT.TABLES WHERE TABSCHEMA = CURRENT SCHEMA AND TABNAME = 'GRAEAE_AUDIT_LOG') THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE graeae_audit_log (
        id VARCHAR(36) NOT NULL PRIMARY KEY,
        sequence_num BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,
        consultation_id VARCHAR(36),
        prompt CLOB NOT NULL,
        prompt_hash VARCHAR(64),
        provider VARCHAR(50) NOT NULL,
        model VARCHAR(100),
        response_text CLOB,
        response_hash VARCHAR(64) NOT NULL,
        chain_hash VARCHAR(64) NOT NULL,
        prev_id VARCHAR(36),
        prev_chain_hash VARCHAR(64),
        task_type VARCHAR(100),
        quality_score DOUBLE,
        latency_ms INTEGER,
        cost_usd DOUBLE,
        created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
      )';
  END IF;
END@
BEGIN NOT ATOMIC
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX idx_graeae_audit_log_consultation ON graeae_audit_log(consultation_id)';
END@
BEGIN NOT ATOMIC
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX idx_graeae_audit_log_created_at ON graeae_audit_log(created_at DESC)';
END@
BEGIN NOT ATOMIC
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX idx_graeae_audit_log_chain_hash ON graeae_audit_log(chain_hash)';
END@

BEGIN NOT ATOMIC
  IF NOT EXISTS (SELECT 1 FROM SYSCAT.TABLES WHERE TABSCHEMA = CURRENT SCHEMA AND TABNAME = 'CONSULTATION_MEMORY_REFS') THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE consultation_memory_refs (
        id VARCHAR(36) NOT NULL PRIMARY KEY,
        consultation_id VARCHAR(36) NOT NULL,
        memory_id VARCHAR(100),
        relevance_score DOUBLE,
        injected_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        CONSTRAINT unique_consultation_memory UNIQUE (consultation_id, memory_id)
      )';
  END IF;
END@
BEGIN NOT ATOMIC
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX idx_consultation_memory_refs_consultation ON consultation_memory_refs(consultation_id)';
END@
BEGIN NOT ATOMIC
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX idx_consultation_memory_refs_memory ON consultation_memory_refs(memory_id)';
END@
