-- migration: 0038_oauth_sessions_consultations
-- Db2 mirror of Oracle 0038_oauth_sessions_consultations.
-- Statement terminator: @

CREATE TABLE oauth_tokens (
  token CHAR(32) FOR BIT DATA NOT NULL PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  provider VARCHAR(100) NOT NULL,
  scopes CLOB(1M) INLINE LENGTH 4096
    CHECK (scopes IS JSON FORMAT JSON STRICT),
  expires_at TIMESTAMP,
  refresh_token VARCHAR(1000),
  created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
  last_used_at TIMESTAMP
)@

CREATE TABLE oauth_state (
  state CHAR(32) FOR BIT DATA NOT NULL PRIMARY KEY,
  provider VARCHAR(100) NOT NULL,
  csrf_token VARCHAR(500) NOT NULL,
  return_url VARCHAR(1000),
  created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL
)@

ALTER TABLE sessions ADD COLUMN session_id CHAR(16) FOR BIT DATA@
ALTER TABLE sessions ADD COLUMN started_at TIMESTAMP DEFAULT CURRENT TIMESTAMP@
ALTER TABLE sessions ADD COLUMN last_active_at TIMESTAMP DEFAULT CURRENT TIMESTAMP@
ALTER TABLE sessions ADD COLUMN expires_at TIMESTAMP@
ALTER TABLE sessions ADD COLUMN metadata CLOB(1M) INLINE LENGTH 4096
  CHECK (metadata IS JSON FORMAT JSON STRICT)@

CREATE UNIQUE INDEX idx_sessions_session_id ON sessions(session_id)@
CREATE INDEX idx_sessions_session_expires ON sessions(expires_at)@

CREATE TABLE session_logs (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id CHAR(16) FOR BIT DATA NOT NULL,
  event_kind VARCHAR(100) NOT NULL,
  payload CLOB(1M) INLINE LENGTH 4096
    CHECK (payload IS JSON FORMAT JSON STRICT),
  ts TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)@

CREATE INDEX idx_session_logs_session_ts ON session_logs(session_id, ts)@

CREATE TABLE consultations (
  id CHAR(16) FOR BIT DATA NOT NULL PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  prompt CLOB NOT NULL,
  task_type VARCHAR(100),
  mode VARCHAR(50),
  status VARCHAR(50) DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
  completed_at TIMESTAMP
)@

CREATE INDEX idx_consultations_user_created ON consultations(user_id, created_at DESC)@
CREATE INDEX idx_consultations_status_created ON consultations(status, created_at DESC)@

CREATE TABLE consultation_responses (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consultation_id CHAR(16) FOR BIT DATA NOT NULL,
  provider VARCHAR(100) NOT NULL,
  model_id VARCHAR(200) NOT NULL,
  response CLOB NOT NULL,
  final_score DOUBLE,
  tokens_in INTEGER,
  tokens_out INTEGER,
  latency_ms INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)@

CREATE INDEX idx_consultation_responses_consultation
  ON consultation_responses(consultation_id, id)@
