-- Oracle 26ai / 23c core MNEMOS schema bootstrap
-- Generated with Codex assistance for Oracle port M7
-- Minimal but sufficient for CHARON import + sidecars

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR2(100) PRIMARY KEY,
    display_name VARCHAR2(200),
    email VARCHAR2(200),
    role VARCHAR2(50) DEFAULT 'user',
    namespace VARCHAR2(100) DEFAULT 'default',
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS memories (
    id VARCHAR2(100) PRIMARY KEY,
    content CLOB,
    category VARCHAR2(100),
    subcategory VARCHAR2(100),
    metadata CLOB,
    quality_rating NUMBER(5,2) DEFAULT 50,
    compressed_content CLOB,
    verbatim_content CLOB,
    owner_id VARCHAR2(100) DEFAULT 'default',
    namespace VARCHAR2(100) DEFAULT 'default',
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    external_id VARCHAR2(200)
);

CREATE INDEX IF NOT EXISTS idx_memories_owner_ns ON memories(owner_id, namespace);
CREATE INDEX IF NOT EXISTS idx_memories_category ON memories(category);

CREATE TABLE IF NOT EXISTS memory_versions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id VARCHAR2(100) REFERENCES memories(id),
    commit_hash VARCHAR2(128),
    content CLOB,
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS kg_triples (
    id VARCHAR2(100) PRIMARY KEY,
    subject VARCHAR2(500),
    predicate VARCHAR2(200),
    object CLOB,
    confidence NUMBER(5,4),
    source_memory_id VARCHAR2(100),
    owner_id VARCHAR2(100),
    namespace VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS compression_manifest (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id VARCHAR2(100),
    tier NUMBER,
    ratio NUMBER,
    model VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS deletion_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id VARCHAR2(100),
    requested_at DATE DEFAULT SYSDATE,
    executed_at DATE,
    status VARCHAR2(20)
);

-- Sessions & related (minimal)
CREATE TABLE IF NOT EXISTS sessions (
    id VARCHAR2(100) PRIMARY KEY,
    user_id VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS session_messages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR2(100),
    role VARCHAR2(20),
    content CLOB,
    created_at DATE DEFAULT SYSDATE
);
