-- migration: 0038_oauth_sessions_consultations
-- Oracle OAuth token/state, protocol sessions, consultation response store.

CREATE TABLE IF NOT EXISTS oauth_tokens (
  token RAW(32) PRIMARY KEY,
  user_id VARCHAR2(100) NOT NULL,
  provider VARCHAR2(100) NOT NULL,
  scopes CLOB CHECK (scopes IS JSON),
  expires_at TIMESTAMP WITH TIME ZONE,
  refresh_token VARCHAR2(1000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  last_used_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS oauth_state (
  state RAW(32) PRIMARY KEY,
  provider VARCHAR2(100) NOT NULL,
  csrf_token VARCHAR2(500) NOT NULL,
  return_url VARCHAR2(1000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

DECLARE
  v_count NUMBER;
  PROCEDURE add_col(p_table VARCHAR2, p_col VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count
      FROM user_tab_columns
     WHERE table_name = UPPER(p_table)
       AND column_name = UPPER(p_col);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_ddl || ')';
    END IF;
  END;
BEGIN
  add_col('sessions', 'session_id', 'session_id RAW(16)');
  add_col('sessions', 'started_at', 'started_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP');
  add_col('sessions', 'last_active_at', 'last_active_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP');
  add_col('sessions', 'expires_at', 'expires_at TIMESTAMP WITH TIME ZONE');
  add_col('sessions', 'metadata', 'metadata CLOB CHECK (metadata IS JSON)');
END;
/

CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_session_id ON sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_session_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS session_logs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id RAW(16) NOT NULL,
  event_kind VARCHAR2(100) NOT NULL,
  payload CLOB CHECK (payload IS JSON),
  ts TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_session_logs_session_ts ON session_logs(session_id, ts);

CREATE TABLE IF NOT EXISTS consultations (
  id RAW(16) PRIMARY KEY,
  user_id VARCHAR2(100) NOT NULL,
  prompt CLOB NOT NULL,
  task_type VARCHAR2(100),
  "mode" VARCHAR2(50),
  status VARCHAR2(50) DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_consultations_user_created ON consultations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consultations_status_created ON consultations(status, created_at DESC);

CREATE TABLE IF NOT EXISTS consultation_responses (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consultation_id RAW(16) NOT NULL,
  provider VARCHAR2(100) NOT NULL,
  model_id VARCHAR2(200) NOT NULL,
  response CLOB NOT NULL,
  final_score NUMBER,
  tokens_in NUMBER,
  tokens_out NUMBER,
  latency_ms NUMBER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_consultation_responses_consultation
  ON consultation_responses(consultation_id, id);
