-- Durable content-free outbox. Publishers assign sequence after mutation commit.
CREATE TABLE IF NOT EXISTS federation_change_clock (id INTEGER PRIMARY KEY, value BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS federation_changes (event_id INTEGER PRIMARY KEY AUTOINCREMENT, seq INTEGER,memory_id TEXT NOT NULL,changed_at TEXT NOT NULL,old_namespace TEXT,old_category TEXT,old_public INTEGER NOT NULL,old_exportable INTEGER NOT NULL,new_namespace TEXT,new_category TEXT,new_public INTEGER NOT NULL,new_exportable INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS federation_receive_state (peer_name TEXT NOT NULL,remote_id TEXT NOT NULL,last_sequence BIGINT,remote_updated TEXT,withdrawn INTEGER NOT NULL,PRIMARY KEY(peer_name,remote_id));
CREATE TABLE IF NOT EXISTS federation_peer_cursors (peer_id TEXT PRIMARY KEY,cursor_value VARCHAR(2048),filter_signature VARCHAR(64));
CREATE INDEX IF NOT EXISTS idx_fed_changes_memory_seq ON federation_changes(memory_id,seq);

INSERT OR IGNORE INTO federation_change_clock(id,value) VALUES(1,0);
CREATE TRIGGER IF NOT EXISTS fed_journal_insert AFTER INSERT ON memories WHEN (NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault'))
BEGIN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT NEW.id,strftime('%Y-%m-%dT%H:%M:%f+00:00','now'),NULL,NULL,0,0,NEW.namespace,NEW.category,CASE WHEN (NEW.permission_mode % 10)>=4 THEN 1 ELSE 0 END,CASE WHEN NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault') AND NEW.deleted_at IS NULL AND NEW.archived_at IS NULL AND NEW.consolidated_into IS NULL THEN 1 ELSE 0 END;
END;
CREATE TRIGGER IF NOT EXISTS fed_journal_update AFTER UPDATE ON memories WHEN ((OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault')) OR (NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault'))) AND (OLD.federation_source IS NOT NEW.federation_source OR OLD.content IS NOT NEW.content OR OLD.category IS NOT NEW.category OR OLD.subcategory IS NOT NEW.subcategory OR OLD.namespace IS NOT NEW.namespace OR OLD.owner_id IS NOT NEW.owner_id OR OLD.permission_mode IS NOT NEW.permission_mode OR OLD.deleted_at IS NOT NEW.deleted_at OR OLD.archived_at IS NOT NEW.archived_at OR OLD.consolidated_into IS NOT NEW.consolidated_into OR OLD.updated IS NOT NEW.updated OR OLD.embedding IS NOT NEW.embedding OR OLD.metadata IS NOT NEW.metadata OR OLD.verbatim_content IS NOT NEW.verbatim_content OR OLD.source_model IS NOT NEW.source_model OR OLD.source_provider IS NOT NEW.source_provider OR OLD.source_agent IS NOT NEW.source_agent OR OLD.source_session IS NOT NEW.source_session)
BEGIN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT NEW.id,strftime('%Y-%m-%dT%H:%M:%f+00:00','now'),OLD.namespace,OLD.category,CASE WHEN (OLD.permission_mode % 10)>=4 THEN 1 ELSE 0 END,CASE WHEN OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault') AND OLD.deleted_at IS NULL AND OLD.archived_at IS NULL AND OLD.consolidated_into IS NULL THEN 1 ELSE 0 END,NEW.namespace,NEW.category,CASE WHEN (NEW.permission_mode % 10)>=4 THEN 1 ELSE 0 END,CASE WHEN NEW.federation_source IS NULL AND (NEW.namespace IS NULL OR NEW.namespace<>'vault') AND NEW.deleted_at IS NULL AND NEW.archived_at IS NULL AND NEW.consolidated_into IS NULL THEN 1 ELSE 0 END;
END;
CREATE TRIGGER IF NOT EXISTS fed_journal_delete AFTER DELETE ON memories WHEN (OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault'))
BEGIN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT OLD.id,strftime('%Y-%m-%dT%H:%M:%f+00:00','now'),OLD.namespace,OLD.category,CASE WHEN (OLD.permission_mode % 10)>=4 THEN 1 ELSE 0 END,CASE WHEN OLD.federation_source IS NULL AND (OLD.namespace IS NULL OR OLD.namespace<>'vault') AND OLD.deleted_at IS NULL AND OLD.archived_at IS NULL AND OLD.consolidated_into IS NULL THEN 1 ELSE 0 END,NULL,NULL,0,0;
END;
BEGIN;
INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT m.id,strftime('%Y-%m-%dT%H:%M:%f+00:00','now'),NULL,NULL,0,0,m.namespace,m.category,CASE WHEN (m.permission_mode % 10)>=4 THEN 1 ELSE 0 END,CASE WHEN m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault') AND m.deleted_at IS NULL AND m.archived_at IS NULL AND m.consolidated_into IS NULL THEN 1 ELSE 0 END FROM memories m WHERE (m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault')) AND NOT EXISTS(SELECT 1 FROM federation_changes e WHERE e.memory_id=m.id);
COMMIT;
CREATE INDEX IF NOT EXISTS idx_fed_changes_pending ON federation_changes(seq,event_id);
