--#SET TERMINATOR @
-- 0002_graeae.sql — Db2 12.1.5 parity backfill for GRAEAE tables.
-- App-side generates UUIDs; duplicate objects are ignored for replay safety.

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE graeae_consultations (
      id VARCHAR(36) NOT NULL,
      prompt CLOB(4M) NOT NULL,
      task_type VARCHAR(100),
      context_uncompressed CLOB(4M),
      context_compressed CLOB(4M),
      context_quality_rating INTEGER,
      context_quality_summary CLOB(1M) CHECK (SYSTOOLS.JSON2BSON(context_quality_summary) IS NOT NULL),
      compression_manifest CLOB(1M) CHECK (SYSTOOLS.JSON2BSON(compression_manifest) IS NOT NULL),
      context_memory_ids CLOB(1M) CHECK (SYSTOOLS.JSON2BSON(context_memory_ids) IS NOT NULL),
      consensus_response CLOB(4M) NOT NULL,
      consensus_score DOUBLE,
      winning_muse VARCHAR(100),
      cost DOUBLE,
      latency_ms INTEGER,
      mode VARCHAR(50),
      created TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
      model_variants CLOB(1M) CHECK (SYSTOOLS.JSON2BSON(model_variants) IS NOT NULL),
      CONSTRAINT pk_graeae_consultations PRIMARY KEY (id),
      CONSTRAINT valid_quality CHECK (context_quality_rating IS NULL OR (context_quality_rating >= 0 AND context_quality_rating <= 100)),
      CONSTRAINT valid_consensus_score CHECK (consensus_score IS NULL OR (consensus_score >= 0 AND consensus_score <= 1.0))
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE graeae_audit_log (
      id VARCHAR(36) NOT NULL,
      sequence_num BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      consultation_id VARCHAR(36),
      prompt CLOB(4M) NOT NULL,
      prompt_hash VARCHAR(64),
      provider VARCHAR(50) NOT NULL,
      model VARCHAR(100),
      response_text CLOB(4M),
      response_hash VARCHAR(64) NOT NULL,
      chain_hash VARCHAR(64) NOT NULL,
      prev_id VARCHAR(36),
      prev_chain_hash VARCHAR(64),
      task_type VARCHAR(100),
      quality_score DOUBLE,
      latency_ms INTEGER,
      cost_usd DOUBLE,
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT pk_graeae_audit_log PRIMARY KEY (id),
      CONSTRAINT uq_graeae_audit_seq UNIQUE (sequence_num),
      CONSTRAINT fk_audit_log_consultation FOREIGN KEY (consultation_id) REFERENCES graeae_consultations(id) ON DELETE CASCADE,
      CONSTRAINT valid_chain_hash CHECK (length(chain_hash) = 64),
      CONSTRAINT valid_response_hash CHECK (length(response_hash) = 64)
    )';
END@

BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END; EXECUTE IMMEDIATE 'CREATE INDEX idx_graeae_audit_log_consultation ON graeae_audit_log(consultation_id)'; END@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END; EXECUTE IMMEDIATE 'CREATE INDEX idx_graeae_audit_log_created_at ON graeae_audit_log(created_at DESC)'; END@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END; EXECUTE IMMEDIATE 'CREATE INDEX idx_graeae_audit_log_chain_hash ON graeae_audit_log(chain_hash)'; END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE consultation_memory_refs (
      id VARCHAR(36) NOT NULL,
      consultation_id VARCHAR(36) NOT NULL,
      memory_id VARCHAR(100),
      relevance_score DOUBLE,
      injected_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT pk_consultation_memory_refs PRIMARY KEY (id),
      CONSTRAINT fk_cmr_consultation FOREIGN KEY (consultation_id) REFERENCES graeae_consultations(id) ON DELETE CASCADE,
      CONSTRAINT fk_cmr_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE SET NULL,
      CONSTRAINT unique_consultation_memory UNIQUE (consultation_id, memory_id)
    )';
END@

BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END; EXECUTE IMMEDIATE 'CREATE INDEX idx_consultation_memory_refs_consultation ON consultation_memory_refs(consultation_id)'; END@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END; EXECUTE IMMEDIATE 'CREATE INDEX idx_consultation_memory_refs_memory ON consultation_memory_refs(memory_id)'; END@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END; EXECUTE IMMEDIATE 'CREATE INDEX idx_consultation_memory_refs_injected_at ON consultation_memory_refs(injected_at DESC)'; END@
