--#SET TERMINATOR @
-- migration: 0024_hive_events
-- target:    IBM Db2 12.1.5

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE hive_events (
      id         BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100) NOT NULL,
      ts         DOUBLE          NOT NULL,
      kind       VARCHAR(64)     NOT NULL,
      payload    CLOB(2M) INLINE LENGTH 4096
        CHECK (SYSTOOLS.JSON2BSON(payload) IS NOT NULL) NOT NULL,
      agent_urn  VARCHAR(256),
      CONSTRAINT pk_hive_events PRIMARY KEY (id)
    )';
END@

BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX ix_hive_events_ts      ON hive_events(ts DESC)';
END@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX ix_hive_events_kind    ON hive_events(kind)';
END@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX ix_hive_events_agent   ON hive_events(agent_urn)';
END@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE INDEX ix_hive_events_kind_ts ON hive_events(kind, ts DESC)';
END@
