-- Durable content-free outbox. Publishers assign sequence after mutation commit.
--#SET TERMINATOR @
CREATE TABLE federation_change_clock (id INTEGER PRIMARY KEY, value BIGINT NOT NULL)@
CREATE TABLE federation_changes (event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, seq BIGINT,memory_id VARCHAR(255) NOT NULL,changed_at TIMESTAMP(6) NOT NULL,old_namespace VARCHAR(255),old_category VARCHAR(255),old_public INTEGER NOT NULL,old_exportable INTEGER NOT NULL,new_namespace VARCHAR(255),new_category VARCHAR(255),new_public INTEGER NOT NULL,new_exportable INTEGER NOT NULL)@
CREATE TABLE federation_receive_state (peer_name VARCHAR(255) NOT NULL,remote_id VARCHAR(255) NOT NULL,last_sequence BIGINT,remote_updated TIMESTAMP(6),withdrawn INTEGER NOT NULL,PRIMARY KEY(peer_name,remote_id))@
CREATE TABLE federation_peer_cursors (peer_id VARCHAR(255) PRIMARY KEY,cursor_value VARCHAR(2048),filter_signature VARCHAR(64))@
CREATE INDEX idx_fed_changes_memory_seq ON federation_changes(memory_id,seq)@

MERGE INTO federation_change_clock c USING (VALUES 1) s(id) ON c.id=s.id WHEN NOT MATCHED THEN INSERT(id,value) VALUES(1,0)@
CREATE OR REPLACE TRIGGER fed_journal_insert AFTER INSERT ON memories REFERENCING NEW AS n FOR EACH ROW MODE DB2SQL
WHEN ((n.federation_source IS NULL AND (n.namespace IS NULL OR n.namespace<>'vault')))
BEGIN ATOMIC
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT n.id,CURRENT_TIMESTAMP,NULL,NULL,0,0,n.namespace,n.category,CASE WHEN MOD(n.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN n.federation_source IS NULL AND (n.namespace IS NULL OR n.namespace<>'vault') AND n.deleted_at IS NULL AND n.archived_at IS NULL AND n.consolidated_into IS NULL THEN 1 ELSE 0 END FROM SYSIBM.SYSDUMMY1;
END@
CREATE OR REPLACE TRIGGER fed_journal_update AFTER UPDATE OF content,category,subcategory,namespace,owner_id,permission_mode,deleted_at,archived_at,consolidated_into,updated,embedding,metadata,verbatim_content,source_model,source_provider,source_agent,source_session ON memories REFERENCING OLD AS o NEW AS n FOR EACH ROW MODE DB2SQL
WHEN ((o.federation_source IS NULL AND (o.namespace IS NULL OR o.namespace<>'vault')) OR (n.federation_source IS NULL AND (n.namespace IS NULL OR n.namespace<>'vault')))
BEGIN ATOMIC
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT n.id,CURRENT_TIMESTAMP,o.namespace,o.category,CASE WHEN MOD(o.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN o.federation_source IS NULL AND (o.namespace IS NULL OR o.namespace<>'vault') AND o.deleted_at IS NULL AND o.archived_at IS NULL AND o.consolidated_into IS NULL THEN 1 ELSE 0 END,n.namespace,n.category,CASE WHEN MOD(n.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN n.federation_source IS NULL AND (n.namespace IS NULL OR n.namespace<>'vault') AND n.deleted_at IS NULL AND n.archived_at IS NULL AND n.consolidated_into IS NULL THEN 1 ELSE 0 END FROM SYSIBM.SYSDUMMY1;
END@
CREATE OR REPLACE TRIGGER fed_journal_delete AFTER DELETE ON memories REFERENCING OLD AS o  FOR EACH ROW MODE DB2SQL
WHEN ((o.federation_source IS NULL AND (o.namespace IS NULL OR o.namespace<>'vault')))
BEGIN ATOMIC
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT o.id,CURRENT_TIMESTAMP,o.namespace,o.category,CASE WHEN MOD(o.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN o.federation_source IS NULL AND (o.namespace IS NULL OR o.namespace<>'vault') AND o.deleted_at IS NULL AND o.archived_at IS NULL AND o.consolidated_into IS NULL THEN 1 ELSE 0 END,NULL,NULL,0,0 FROM SYSIBM.SYSDUMMY1;
END@
INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT m.id,CURRENT_TIMESTAMP,NULL,NULL,0,0,m.namespace,m.category,CASE WHEN MOD(m.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault') AND m.deleted_at IS NULL AND m.archived_at IS NULL AND m.consolidated_into IS NULL THEN 1 ELSE 0 END FROM memories m WHERE (m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault')) AND NOT EXISTS(SELECT 1 FROM federation_changes e WHERE e.memory_id=m.id)@
CREATE INDEX idx_fed_changes_pending ON federation_changes(seq,event_id)@
