-- MNEMOS MySQL 8.0 schema mirror of the canonical PostgreSQL migrations.
-- Dialect notes: UUID/BYTEA are app-supplied CHAR/VARCHAR/VARBINARY values,
-- JSONB/arrays/vector columns are JSON, TIMESTAMPTZ is DATETIME(6), BOOLEAN is
-- TINYINT(1), and all tables use InnoDB + utf8mb4. MySQL has no partial
-- indexes, so indexes that mirror PostgreSQL partial indexes are plain indexes.

CREATE TABLE IF NOT EXISTS users (
  id              VARCHAR(255) PRIMARY KEY,
  display_name    TEXT,
  email           VARCHAR(320) UNIQUE,
  role            VARCHAR(32) NOT NULL DEFAULT 'user',
  created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  namespace       VARCHAR(255) NOT NULL DEFAULT 'default',
  username        VARCHAR(255),
  UNIQUE KEY uq_users_username (username),
  KEY idx_users_namespace (namespace),
  CHECK (role IN ('user', 'root'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `groups` (
  id              VARCHAR(255) PRIMARY KEY,
  display_name    TEXT,
  created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_groups (
  user_id         VARCHAR(255) NOT NULL,
  group_id        VARCHAR(255) NOT NULL,
  is_admin        TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, group_id),
  KEY idx_user_groups_group (group_id),
  CONSTRAINT fk_user_groups_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_groups_group FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS api_keys (
  id              CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  user_id         VARCHAR(255) NOT NULL,
  key_hash        VARCHAR(512) NOT NULL UNIQUE,
  key_prefix      VARCHAR(255) NOT NULL,
  label           TEXT,
  created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_used       DATETIME(6),
  revoked         TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_api_keys_user (user_id),
  KEY idx_api_keys_revoked (revoked),
  CONSTRAINT fk_api_keys_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memories (
  id                          VARCHAR(255) PRIMARY KEY,
  content                     LONGTEXT NOT NULL,
  content_hash                VARCHAR(64),
  category                    VARCHAR(255) NOT NULL,
  task_type                   VARCHAR(255),
  created                     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated                     DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  compressed_content          LONGTEXT,
  compression_method          VARCHAR(50),
  compression_ratio           DOUBLE,
  compression_manifest        JSON,
  quality_rating              INT,
  quality_summary             JSON,
  original_reference          VARCHAR(255),
  compressed_at               DATETIME(6),
  compressed_by               VARCHAR(50),
  compression_reason          VARCHAR(255),
  is_original                 TINYINT(1) NOT NULL DEFAULT 1,
  is_compressed               TINYINT(1) GENERATED ALWAYS AS (compressed_content IS NOT NULL) STORED,
  original_token_count        INT,
  compressed_token_count      INT,
  embedding                   JSON,
  subcategory                 TEXT,
  metadata                    JSON DEFAULT (JSON_OBJECT()),
  verbatim_content            LONGTEXT,
  owner_id                    VARCHAR(255) NOT NULL DEFAULT 'default',
  group_id                    VARCHAR(255),
  namespace                   VARCHAR(255) NOT NULL DEFAULT 'default',
  permission_mode             SMALLINT NOT NULL DEFAULT 600,
  source_model                TEXT,
  source_provider             TEXT,
  source_session              TEXT,
  source_agent                TEXT,
  llm_optimized               TINYINT(1) NOT NULL DEFAULT 0,
  optimized_at                DATETIME(6),
  morpheus_run_id             CHAR(36),
  source_memories             JSON,
  source_memory_ids           JSON,
  provenance                  TEXT,
  federation_source           TEXT,
  federation_remote_updated   DATETIME(6),
  federation_synced_at        DATETIME(6),
  recall_count                INT NOT NULL DEFAULT 0,
  last_recalled_at            DATETIME(6),
  consolidated_into           VARCHAR(255),
  consolidated_at             DATETIME(6),
  import_chunk_key            TEXT,
  archived_at                 DATETIME(6),
  deleted_at                  DATETIME(6),
  triples_extracted_at        DATETIME(6),
  federation_last_pushed_at   DATETIME(6),
  federation_push_peer        TEXT,
  KEY idx_memories_category (category),
  KEY idx_memories_task_type (task_type),
  KEY idx_memories_created (created),
  KEY idx_memories_updated_id (updated, id),
  KEY idx_memories_original_reference (original_reference),
  KEY idx_memories_owner_namespace (owner_id, namespace),
  KEY idx_memories_group_id (group_id),
  KEY idx_memories_content_hash (content_hash),
  KEY idx_memories_morpheus_run (morpheus_run_id),
  KEY idx_memories_last_recalled_at (last_recalled_at),
  FULLTEXT KEY idx_memories_ft (content),
  CHECK (quality_rating IS NULL OR (quality_rating >= 0 AND quality_rating <= 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_embeddings (
  memory_id       VARCHAR(255) PRIMARY KEY,
  embedding       JSON NOT NULL,
  updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_memory_embeddings_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS kg_triples (
  id                    VARCHAR(255) PRIMARY KEY,
  subject               TEXT NOT NULL,
  predicate             TEXT NOT NULL,
  object                TEXT NOT NULL,
  subject_type          TEXT,
  object_type           TEXT,
  valid_from            DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  valid_until           DATETIME(6),
  memory_id             VARCHAR(255),
  confidence            DOUBLE NOT NULL DEFAULT 1.0,
  created               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  owner_id              VARCHAR(255),
  namespace             VARCHAR(255),
  deleted_at            DATETIME(6),
  extracted_by_run_id   CHAR(36),
  KEY idx_kg_memory_id (memory_id),
  KEY idx_kg_owner_namespace (owner_id, namespace),
  CONSTRAINT fk_kg_triples_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_versions (
  id                  CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  memory_id           VARCHAR(255) NOT NULL,
  version_num         INT NOT NULL,
  content             LONGTEXT NOT NULL,
  category            TEXT NOT NULL,
  subcategory         TEXT,
  metadata            JSON,
  verbatim_content    LONGTEXT,
  owner_id            VARCHAR(255) NOT NULL,
  namespace           VARCHAR(255) NOT NULL,
  permission_mode     SMALLINT NOT NULL,
  source_model        TEXT,
  source_provider     TEXT,
  source_session      TEXT,
  source_agent        TEXT,
  snapshot_at         DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  snapshot_by         TEXT,
  change_type         VARCHAR(32) NOT NULL,
  commit_hash         VARCHAR(255) NOT NULL,
  parent_version_id   CHAR(36),
  branch              VARCHAR(255) NOT NULL DEFAULT 'main',
  merge_parents       JSON,
  snapshot_new_values JSON,
  deleted_at          DATETIME(6),
  UNIQUE KEY uq_memory_versions_memory_branch_version (memory_id, branch, version_num),
  KEY idx_mv_memory_id (memory_id),
  KEY idx_mv_snapshot_at (snapshot_at),
  KEY idx_mv_parent_version (parent_version_id),
  KEY idx_mv_deleted (deleted_at),
  CHECK (change_type IN ('create', 'update', 'delete')),
  CONSTRAINT fk_mv_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE,
  CONSTRAINT fk_mv_parent FOREIGN KEY (parent_version_id) REFERENCES memory_versions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_branches (
  id               CHAR(36) DEFAULT (UUID()),
  memory_id        VARCHAR(255) NOT NULL,
  name             VARCHAR(255) NOT NULL,
  head_version_id  CHAR(36),
  created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by       TEXT,
  deleted_at       DATETIME(6),
  PRIMARY KEY (memory_id, name),
  KEY idx_memory_branches_id (id),
  KEY idx_memory_branches_head (head_version_id),
  CONSTRAINT fk_memory_branches_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE,
  CONSTRAINT fk_memory_branches_head FOREIGN KEY (head_version_id) REFERENCES memory_versions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS compression_quality_log (
  id                       CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  memory_id                VARCHAR(255),
  original_token_count     INT,
  compressed_token_count   INT,
  compression_ratio        DOUBLE,
  compression_method       VARCHAR(50),
  quality_rating           INT,
  quality_summary          JSON,
  compression_manifest     JSON,
  created                  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  reviewed                 TINYINT(1) DEFAULT 0,
  review_notes             TEXT,
  reviewed_by              VARCHAR(100),
  reviewed_at              DATETIME(6),
  original_content         LONGTEXT,
  compressed_content       LONGTEXT,
  original_tokens          INT,
  compressed_tokens        INT,
  llm_feedback             TEXT,
  owner_id                 VARCHAR(255) NOT NULL DEFAULT 'default',
  KEY idx_compression_log_memory (memory_id),
  KEY idx_compression_log_created (created),
  CHECK (compression_ratio IS NULL OR (compression_ratio > 0 AND compression_ratio <= 10)),
  CHECK (quality_rating IS NULL OR (quality_rating >= 0 AND quality_rating <= 100)),
  CONSTRAINT fk_compression_log_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_compression_queue (
  id               CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  memory_id        VARCHAR(255) NOT NULL,
  owner_id         VARCHAR(255) NOT NULL DEFAULT 'default',
  reason           VARCHAR(32) NOT NULL,
  status           VARCHAR(16) NOT NULL DEFAULT 'pending',
  priority         SMALLINT NOT NULL DEFAULT 0,
  scoring_profile  VARCHAR(32) NOT NULL DEFAULT 'balanced',
  attempts         SMALLINT NOT NULL DEFAULT 0,
  enqueued_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  started_at       DATETIME(6),
  finished_at      DATETIME(6),
  error            TEXT,
  KEY idx_mcq_ready (status, priority, enqueued_at),
  KEY idx_mcq_memory (memory_id),
  KEY idx_mcq_owner (owner_id),
  CHECK (status IN ('pending','running','done','failed')),
  CHECK (reason IN ('on_write','manual','scheduled','reprocess')),
  CHECK (scoring_profile IN ('balanced','quality_first','speed_first','custom')),
  CONSTRAINT fk_mcq_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_compression_candidates (
  id                  CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  memory_id           VARCHAR(255) NOT NULL,
  owner_id            VARCHAR(255) NOT NULL DEFAULT 'default',
  contest_id          CHAR(36) NOT NULL,
  engine_id           VARCHAR(32) NOT NULL,
  engine_version      VARCHAR(32),
  compressed_content  LONGTEXT,
  original_tokens     INT NOT NULL,
  compressed_tokens   INT,
  candidate_content   LONGTEXT,
  candidate_tokens    INT,
  compression_ratio   DOUBLE,
  quality_score       DOUBLE,
  speed_factor        DOUBLE,
  composite_score     DOUBLE,
  scoring_profile     VARCHAR(32) NOT NULL DEFAULT 'balanced',
  elapsed_ms          INT,
  judge_model         VARCHAR(64),
  gpu_used            TINYINT(1) NOT NULL DEFAULT 0,
  is_winner           TINYINT(1) NOT NULL DEFAULT 0,
  reject_reason       VARCHAR(32),
  manifest            JSON,
  created             DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY idx_mcc_memory (memory_id),
  KEY idx_mcc_contest (contest_id),
  KEY idx_mcc_memory_winner (memory_id, is_winner),
  KEY idx_mcc_owner (owner_id),
  KEY idx_mcc_engine (engine_id),
  CHECK (compression_ratio IS NULL OR (compression_ratio > 0 AND compression_ratio <= 10)),
  CHECK (quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 1)),
  CHECK (speed_factor IS NULL OR (speed_factor >= 0 AND speed_factor <= 1)),
  CHECK (reject_reason IS NULL OR reject_reason IN ('quality_floor','no_output','error','inferior','timeout','disabled')),
  CHECK (scoring_profile IN ('balanced','quality_first','speed_first','custom')),
  CHECK (NOT is_winner OR (compressed_content IS NOT NULL AND compression_ratio IS NOT NULL AND composite_score IS NOT NULL)),
  CHECK (is_winner OR reject_reason IS NOT NULL),
  CONSTRAINT fk_mcc_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_compressed_variants (
  memory_id             VARCHAR(255) PRIMARY KEY,
  owner_id              VARCHAR(255) NOT NULL DEFAULT 'default',
  winner_candidate_id   CHAR(36),
  engine_id             VARCHAR(32) NOT NULL,
  engine_version        VARCHAR(32),
  compressed_content    LONGTEXT NOT NULL,
  compressed_tokens     INT,
  compression_ratio     DOUBLE NOT NULL,
  quality_score         DOUBLE,
  composite_score       DOUBLE NOT NULL,
  scoring_profile       VARCHAR(32) NOT NULL DEFAULT 'balanced',
  judge_model           VARCHAR(64),
  selected_at           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY idx_mcv_owner (owner_id),
  KEY idx_mcv_engine (engine_id),
  CHECK (compression_ratio > 0 AND compression_ratio <= 10),
  CHECK (quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 1)),
  CHECK (scoring_profile IN ('balanced','quality_first','speed_first','custom')),
  CONSTRAINT fk_mcv_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcv_candidate FOREIGN KEY (winner_candidate_id) REFERENCES memory_compression_candidates(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS state (
  owner_id       VARCHAR(255) NOT NULL DEFAULT 'default',
  namespace      VARCHAR(255) NOT NULL DEFAULT 'default',
  `key`          VARCHAR(255) NOT NULL,
  value          TEXT NOT NULL,
  updated        DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by     VARCHAR(100),
  version        INT DEFAULT 1,
  deleted_at     DATETIME(6),
  PRIMARY KEY (owner_id, namespace, `key`),
  KEY idx_state_owner (owner_id),
  KEY idx_state_namespace (namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS journal (
  id           CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  entry_date   DATE NOT NULL,
  topic        VARCHAR(100),
  content      LONGTEXT,
  metadata     JSON,
  created      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  owner_id     VARCHAR(255) NOT NULL DEFAULT 'default',
  namespace    VARCHAR(255) NOT NULL DEFAULT 'default',
  deleted_at   DATETIME(6),
  KEY idx_journal_entry_date (entry_date),
  KEY idx_journal_owner_namespace (owner_id, namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS entities (
  id                CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  entity_type       VARCHAR(50) NOT NULL,
  name              VARCHAR(255) NOT NULL,
  description       TEXT,
  metadata          JSON,
  related_entities  JSON,
  created           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated           DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  owner_id          VARCHAR(255) NOT NULL DEFAULT 'default',
  namespace         VARCHAR(255) NOT NULL DEFAULT 'default',
  deleted_at        DATETIME(6),
  UNIQUE KEY uq_entities_owner_namespace_type_name (owner_id, namespace, entity_type, name(150)),
  KEY idx_entities_type (entity_type),
  KEY idx_entities_name (name),
  KEY idx_entities_owner_namespace (owner_id, namespace)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
