-- 0002_graeae.sql — GRAEAE consultation + audit log tables for Oracle 23ai.
-- Ports PG migrations:
--   db/migrations.sql (graeae_consultations baseline)
--   db/migrations_v3_graeae_unified.sql (graeae_audit_log + consultation_memory_refs)
-- App-side generates UUIDs (no DB DEFAULT — clean Oracle DDL).

CREATE TABLE graeae_consultations (
  id VARCHAR2(36) PRIMARY KEY,
  prompt CLOB NOT NULL,
  task_type VARCHAR2(100),
  context_uncompressed CLOB,
  context_compressed CLOB,
  context_quality_rating NUMBER,
  context_quality_summary CLOB CHECK (context_quality_summary IS JSON),
  compression_manifest CLOB CHECK (compression_manifest IS JSON),
  context_memory_ids CLOB CHECK (context_memory_ids IS JSON),
  consensus_response CLOB NOT NULL,
  consensus_score NUMBER,
  winning_muse VARCHAR2(100),
  cost NUMBER,
  latency_ms NUMBER,
  "mode" VARCHAR2(50),
  created TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  model_variants CLOB CHECK (model_variants IS JSON),
  CONSTRAINT valid_quality CHECK (context_quality_rating IS NULL OR (context_quality_rating >= 0 AND context_quality_rating <= 100)),
  CONSTRAINT valid_consensus_score CHECK (consensus_score IS NULL OR (consensus_score >= 0 AND consensus_score <= 1.0))
);

CREATE TABLE graeae_audit_log (
  id VARCHAR2(36) PRIMARY KEY,
  sequence_num NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
  consultation_id VARCHAR2(36),
  prompt CLOB NOT NULL,
  prompt_hash VARCHAR2(64),
  provider VARCHAR2(50) NOT NULL,
  model VARCHAR2(100),
  response_text CLOB,
  response_hash VARCHAR2(64) NOT NULL,
  chain_hash VARCHAR2(64) NOT NULL,
  prev_id VARCHAR2(36),
  prev_chain_hash VARCHAR2(64),
  task_type VARCHAR2(100),
  quality_score NUMBER,
  latency_ms NUMBER,
  cost_usd NUMBER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_audit_log_consultation FOREIGN KEY (consultation_id) REFERENCES graeae_consultations(id) ON DELETE CASCADE,
  CONSTRAINT valid_chain_hash CHECK (length(chain_hash) = 64),
  CONSTRAINT valid_response_hash CHECK (length(response_hash) = 64)
);

CREATE INDEX idx_graeae_audit_log_consultation ON graeae_audit_log(consultation_id);
CREATE INDEX idx_graeae_audit_log_created_at ON graeae_audit_log(created_at DESC);
CREATE INDEX idx_graeae_audit_log_chain_hash ON graeae_audit_log(chain_hash);

CREATE TABLE consultation_memory_refs (
  id VARCHAR2(36) PRIMARY KEY,
  consultation_id VARCHAR2(36) NOT NULL,
  memory_id VARCHAR2(36),
  relevance_score NUMBER,
  injected_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_consultation_memory_refs_consultation FOREIGN KEY (consultation_id) REFERENCES graeae_consultations(id) ON DELETE CASCADE,
  CONSTRAINT fk_consultation_memory_refs_memory FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE SET NULL,
  CONSTRAINT unique_consultation_memory UNIQUE (consultation_id, memory_id)
);

CREATE INDEX idx_consultation_memory_refs_consultation ON consultation_memory_refs(consultation_id);
CREATE INDEX idx_consultation_memory_refs_memory ON consultation_memory_refs(memory_id);
CREATE INDEX idx_consultation_memory_refs_injected_at ON consultation_memory_refs(injected_at DESC);
