-- Durable content-free outbox. Publishers assign sequence after mutation commit.
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE federation_change_clock (id INTEGER PRIMARY KEY, value NUMBER(19) NOT NULL)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE federation_changes (event_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, seq NUMBER(19),memory_id VARCHAR(255) NOT NULL,changed_at TIMESTAMP(6) NOT NULL,old_namespace VARCHAR(255),old_category VARCHAR(255),old_public INTEGER NOT NULL,old_exportable INTEGER NOT NULL,new_namespace VARCHAR(255),new_category VARCHAR(255),new_public INTEGER NOT NULL,new_exportable INTEGER NOT NULL)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE federation_receive_state (peer_name VARCHAR(255) NOT NULL,remote_id VARCHAR(255) NOT NULL,last_sequence NUMBER(19),remote_updated TIMESTAMP(6),withdrawn INTEGER NOT NULL,PRIMARY KEY(peer_name,remote_id))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE federation_peer_cursors (peer_id VARCHAR(255) PRIMARY KEY,cursor_value VARCHAR(2048),filter_signature VARCHAR(64))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_fed_changes_memory_seq ON federation_changes(memory_id,seq)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
MERGE INTO federation_change_clock c USING (SELECT 1 id FROM dual) s ON(c.id=s.id) WHEN NOT MATCHED THEN INSERT(id,value) VALUES(1,0);
CREATE OR REPLACE TRIGGER fed_journal_insert AFTER INSERT ON memories FOR EACH ROW
BEGIN
 IF (:NEW.federation_source IS NULL AND (:NEW.namespace IS NULL OR :NEW.namespace<>'vault')) THEN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) VALUES(:NEW.id,SYS_EXTRACT_UTC(SYSTIMESTAMP),NULL,NULL,0,0,:NEW.namespace,:NEW.category,CASE WHEN MOD(:NEW.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN :NEW.federation_source IS NULL AND (:NEW.namespace IS NULL OR :NEW.namespace<>'vault') AND :NEW.deleted_at IS NULL AND :NEW.archived_at IS NULL AND :NEW.consolidated_into IS NULL THEN 1 ELSE 0 END);
 END IF;
END;
/
CREATE OR REPLACE TRIGGER fed_journal_update AFTER UPDATE OF content,category,subcategory,namespace,owner_id,permission_mode,deleted_at,archived_at,consolidated_into,updated,embedding,metadata,verbatim_content,source_model,source_provider,source_agent,source_session ON memories FOR EACH ROW
BEGIN
 IF (:OLD.federation_source IS NULL AND (:OLD.namespace IS NULL OR :OLD.namespace<>'vault')) OR (:NEW.federation_source IS NULL AND (:NEW.namespace IS NULL OR :NEW.namespace<>'vault')) THEN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) VALUES(:NEW.id,SYS_EXTRACT_UTC(SYSTIMESTAMP),:OLD.namespace,:OLD.category,CASE WHEN MOD(:OLD.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN :OLD.federation_source IS NULL AND (:OLD.namespace IS NULL OR :OLD.namespace<>'vault') AND :OLD.deleted_at IS NULL AND :OLD.archived_at IS NULL AND :OLD.consolidated_into IS NULL THEN 1 ELSE 0 END,:NEW.namespace,:NEW.category,CASE WHEN MOD(:NEW.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN :NEW.federation_source IS NULL AND (:NEW.namespace IS NULL OR :NEW.namespace<>'vault') AND :NEW.deleted_at IS NULL AND :NEW.archived_at IS NULL AND :NEW.consolidated_into IS NULL THEN 1 ELSE 0 END);
 END IF;
END;
/
CREATE OR REPLACE TRIGGER fed_journal_delete AFTER DELETE ON memories FOR EACH ROW
BEGIN
 IF (:OLD.federation_source IS NULL AND (:OLD.namespace IS NULL OR :OLD.namespace<>'vault')) THEN
 INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) VALUES(:OLD.id,SYS_EXTRACT_UTC(SYSTIMESTAMP),:OLD.namespace,:OLD.category,CASE WHEN MOD(:OLD.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN :OLD.federation_source IS NULL AND (:OLD.namespace IS NULL OR :OLD.namespace<>'vault') AND :OLD.deleted_at IS NULL AND :OLD.archived_at IS NULL AND :OLD.consolidated_into IS NULL THEN 1 ELSE 0 END,NULL,NULL,0,0);
 END IF;
END;
/
INSERT INTO federation_changes(memory_id,changed_at,old_namespace,old_category,old_public,old_exportable,new_namespace,new_category,new_public,new_exportable) SELECT m.id,SYS_EXTRACT_UTC(SYSTIMESTAMP),NULL,NULL,0,0,m.namespace,m.category,CASE WHEN MOD(m.permission_mode,10)>=4 THEN 1 ELSE 0 END,CASE WHEN m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault') AND m.deleted_at IS NULL AND m.archived_at IS NULL AND m.consolidated_into IS NULL THEN 1 ELSE 0 END FROM memories m WHERE (m.federation_source IS NULL AND (m.namespace IS NULL OR m.namespace<>'vault')) AND NOT EXISTS(SELECT 1 FROM federation_changes e WHERE e.memory_id=m.id);
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_fed_changes_pending ON federation_changes(seq,event_id)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
