-- SQLite mirror for migrations_model_registry.
-- The logical schema change from the PostgreSQL migration is represented
-- in migrations.sql with SQLite-compatible TEXT/INTEGER/JSON storage and
-- idempotent indexes. PostgreSQL-only GRANT, COMMENT, RLS, advisory-lock,
-- and trigger-function statements are intentionally omitted.
