-- SQLite mirror for migrations_v3_5_entities_namespace_unique.
-- The logical schema change from the PostgreSQL migration is represented
-- in migrations.sql with SQLite-compatible TEXT/INTEGER/JSON storage and
-- idempotent indexes. PostgreSQL-only GRANT, COMMENT, RLS, advisory-lock,
-- and trigger-function statements are intentionally omitted.
