#!/usr/bin/env python3
"""Defensible bake-off v4 — addresses all 6 GRAEAE-flagged fatal flaws.

Fixes:
  1. Scale 10K (not 2K) — escapes L3 cache + DiskANN regime threshold
  2. Recall@10 vs exact baseline (compute exact top-K with index-disabled query)
  3. PG HNSW (not ivfflat) — pgvector 0.5+ stronger default
  4. Multi-knob sweep:
     - PG: hnsw.ef_search 40/100/200
     - DB2: FETCH APPROX FIRST K (no exposed knob in EAP — single point)
     - Oracle: HNSW NEIGHBORS / EFCONSTRUCTION (if vector_memory available)
  5. 1000 queries per measurement (not 50)
  6. Vectors generated by gen_clustered() — Gaussian-clustered (mixture of
     N=20 cluster centers, noise=0.3), more ANN-realistic than pure
     Gaussian. NOT a text-embedding-quality bench: this isolates vector-
     index performance from embedding-model effects. No sentence-transformers
     fallback is implemented today (planned for a v6.x real-corpus bench).
  7. EXPLAIN PLAN capture per query type
  8. Container memory equalized (--shm-size=8g across all)
  9. Per-DB warmup: 50 queries (not 5)
"""

from __future__ import annotations
import asyncio
import json
import os
import random
import statistics
import time
from pathlib import Path

random.seed(42)
N_SEED = int(os.environ.get("BENCH_N", "10000"))
N_QUERY = int(os.environ.get("BENCH_QUERIES", "1000"))
WARMUP = int(os.environ.get("BENCH_WARMUP", "50"))
EMBED_DIM = 768
K = 10
CATS = ["infrastructure", "solutions", "patterns", "decisions", "projects", "standards"]
TAGS = [f"t{i}" for i in range(50)]


def gen_clustered(n, dim, n_clusters=20, noise=0.3):
    """Mixture-of-Gaussians — more ANN-realistic than pure Gaussian.
    Real semantic embeddings cluster around topic centroids."""
    centroids = [[random.gauss(0, 1) for _ in range(dim)] for _ in range(n_clusters)]
    out = []
    for i in range(n):
        c = centroids[i % n_clusters]
        v = [c[j] + random.gauss(0, noise) for j in range(dim)]
        out.append(v)
    return out


def gen_rows(n):
    embs = gen_clustered(n, EMBED_DIM)
    return [
        {
            "id": f"bench-{i:08x}",
            "content": "lorem ipsum " * random.randint(2, 10),
            "category": random.choice(CATS),
            "tag": random.choice(TAGS),
            "embedding": e,
        }
        for i, e in enumerate(embs)
    ]


def pct(s, p):
    s = sorted(s)
    k = int(len(s) * p / 100)
    return s[min(k, len(s) - 1)]


def summ(samples):
    if not samples:
        return None
    return {
        "n": len(samples),
        "p50_ms": round(pct(samples, 50) * 1000, 3),
        "p95_ms": round(pct(samples, 95) * 1000, 3),
        "p99_ms": round(pct(samples, 99) * 1000, 3),
        "min_ms": round(min(samples) * 1000, 3),
        "max_ms": round(max(samples) * 1000, 3),
        "mean_ms": round(statistics.mean(samples) * 1000, 3),
    }


def recall_at_k(returned, expected, k=K):
    """recall@k = |returned ∩ expected| / k"""
    rset = set(returned[:k])
    eset = set(expected[:k])
    return len(rset & eset) / k


# ============== PG HNSW ==============
async def bench_pg(dsn, rows, queries, exact_topk):
    import asyncpg

    pool = await asyncpg.create_pool(dsn, min_size=2, max_size=8, ssl=False, timeout=10, statement_cache_size=256)
    print(f"[pg/HNSW] connected (n={len(rows)})")
    async with pool.acquire() as c:
        await c.execute("CREATE EXTENSION IF NOT EXISTS vector")
        await c.execute("DROP TABLE IF EXISTS bench_memories CASCADE")
        await c.execute(
            f"CREATE TABLE bench_memories (id TEXT PRIMARY KEY, content TEXT, category TEXT, tag TEXT, embedding vector({EMBED_DIM}))"
        )

    # Ingest
    t0 = time.perf_counter()
    async with pool.acquire() as c:
        await c.executemany(
            "INSERT INTO bench_memories(id,content,category,tag,embedding) VALUES($1,$2,$3,$4,$5::vector)",
            [(r["id"], r["content"], r["category"], r["tag"], str(r["embedding"])) for r in rows],
        )
    ingest_s = time.perf_counter() - t0
    print(f"[pg] ingest {len(rows)} in {ingest_s:.2f}s = {len(rows)/ingest_s:.1f} rec/s")

    # Build HNSW
    t0 = time.perf_counter()
    async with pool.acquire() as c:
        await c.execute(
            "CREATE INDEX ix_bench_hnsw ON bench_memories USING hnsw (embedding vector_l2_ops) WITH (m=16, ef_construction=64)"
        )
        await c.execute("CREATE INDEX ix_bench_cat ON bench_memories(category)")
        await c.execute("CREATE INDEX ix_bench_tag ON bench_memories(tag)")
        await c.execute("ANALYZE bench_memories")
    idx_s = time.perf_counter() - t0
    print(f"[pg] HNSW build in {idx_s:.2f}s")

    # Warmup
    async with pool.acquire() as c:
        for qv in queries[:WARMUP]:
            await c.fetch("SELECT id FROM bench_memories ORDER BY embedding <-> $1::vector LIMIT $2", str(qv), K)

    # EXPLAIN for vec search
    explain_text = ""
    async with pool.acquire() as c:
        rows_ex = await c.fetch(
            "EXPLAIN (ANALYZE, BUFFERS) SELECT id FROM bench_memories ORDER BY embedding <-> $1::vector LIMIT $2",
            str(queries[0]),
            K,
        )
        explain_text = "\n".join(r[0] for r in rows_ex)

    results = {
        "engine": "pg-hnsw",
        "n": len(rows),
        "ingest_rec_per_sec": round(len(rows) / ingest_s, 2),
        "ingest_total_sec": round(ingest_s, 2),
        "build_index_sec": round(idx_s, 2),
        "explain_vector": explain_text[:2000],
        "sweep": [],
    }

    # Sweep ef_search 40/100/200
    for ef in [40, 100, 200]:
        async with pool.acquire() as c:
            await c.execute(f"SET hnsw.ef_search = {ef}")
            lat, recalls = [], []
            for i, qv in enumerate(queries):
                t0 = time.perf_counter()
                rs = await c.fetch(
                    "SELECT id FROM bench_memories ORDER BY embedding <-> $1::vector LIMIT $2", str(qv), K
                )
                lat.append(time.perf_counter() - t0)
                if i < len(exact_topk):
                    recalls.append(recall_at_k([r[0] for r in rs], exact_topk[i]))
        results["sweep"].append(
            {
                "knob": f"ef_search={ef}",
                "latency": summ(lat),
                "recall_at_10_mean": round(statistics.mean(recalls), 4) if recalls else None,
                "recall_at_10_min": round(min(recalls), 4) if recalls else None,
            }
        )

    # fetch_by_id
    ids = [r["id"] for r in rows]
    fetch_lat = []
    async with pool.acquire() as c:
        for _ in range(N_QUERY):
            i = random.choice(ids)
            t0 = time.perf_counter()
            await c.fetchrow("SELECT * FROM bench_memories WHERE id=$1", i)
            fetch_lat.append(time.perf_counter() - t0)
    results["fetch_by_id"] = summ(fetch_lat)

    # filter_search
    filt_lat = []
    async with pool.acquire() as c:
        for _ in range(N_QUERY):
            cat, tag = random.choice(CATS), random.choice(TAGS)
            t0 = time.perf_counter()
            await c.fetch("SELECT id FROM bench_memories WHERE category=$1 AND tag=$2 LIMIT 10", cat, tag)
            filt_lat.append(time.perf_counter() - t0)
    results["filter_search"] = summ(filt_lat)

    await pool.close()
    return results


async def pg_exact_topk(dsn, rows, queries):
    """Compute exact top-K via PG with NO index (sequential scan)."""
    import asyncpg

    pool = await asyncpg.create_pool(dsn, min_size=1, max_size=2, ssl=False, timeout=30, statement_cache_size=128)
    async with pool.acquire() as c:
        # Disable index scan to force exact scan
        await c.execute("SET enable_indexscan = off")
        await c.execute("SET enable_bitmapscan = off")
        topk = []
        for qv in queries:
            rs = await c.fetch("SELECT id FROM bench_memories ORDER BY embedding <-> $1::vector LIMIT $2", str(qv), K)
            topk.append([r[0] for r in rs])
    await pool.close()
    return topk


# ============== DB2 DiskANN ==============
def bench_db2(dsn, rows, queries, exact_topk):
    import ibm_db
    import re

    m = re.match(r"db2://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)", dsn)
    cs = f"DATABASE={m.group(5)};HOSTNAME={m.group(3)};PORT={m.group(4)};PROTOCOL=TCPIP;UID={m.group(1)};PWD={m.group(2)};"
    conn = ibm_db.connect(cs, "", "")
    print(f"[db2/DiskANN] connected (n={len(rows)})")
    try:
        ibm_db.exec_immediate(conn, "DROP TABLE bench_memories")
    except Exception:
        pass
    ibm_db.exec_immediate(
        conn,
        f"CREATE TABLE bench_memories(id VARCHAR(64) NOT NULL PRIMARY KEY, content CLOB, category VARCHAR(64), tag VARCHAR(64), embedding VECTOR({EMBED_DIM}, FLOAT32))",
    )

    t0 = time.perf_counter()
    stmt = ibm_db.prepare(
        conn,
        f"INSERT INTO bench_memories(id,content,category,tag,embedding) VALUES (?,?,?,?,VECTOR(?, {EMBED_DIM}, FLOAT32))",
    )
    for r in rows:
        ibm_db.execute(stmt, (r["id"], r["content"], r["category"], r["tag"], json.dumps(r["embedding"])))
    ibm_db.commit(conn)
    ingest_s = time.perf_counter() - t0
    print(f"[db2] ingest {len(rows)} in {ingest_s:.2f}s = {len(rows)/ingest_s:.1f} rec/s")

    t0 = time.perf_counter()
    try:
        ibm_db.exec_immediate(conn, "CREATE INDEX ix_bench_cat ON bench_memories(category)")
    except Exception:
        pass
    try:
        ibm_db.exec_immediate(conn, "CREATE INDEX ix_bench_tag ON bench_memories(tag)")
    except Exception:
        pass
    indexed = False
    try:
        ibm_db.exec_immediate(
            conn, "CREATE VECTOR INDEX ix_bench_emb ON bench_memories(embedding) WITH DISTANCE EUCLIDEAN"
        )
        indexed = True
        print("[db2] DiskANN built")
    except Exception as e:
        print(f"[db2] vec idx: {str(e)[:120]}")
    # Full RUNSTATS — WITH DISTRIBUTION AND DETAILED INDEXES ALL
    try:
        ibm_db.exec_immediate(
            conn,
            "CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE DB2INST1.BENCH_MEMORIES WITH DISTRIBUTION AND DETAILED INDEXES ALL')",
        )
        print("[db2] RUNSTATS full")
    except Exception as e:
        print(f"[db2] runstats: {str(e)[:120]}")
    idx_s = time.perf_counter() - t0

    # EXPLAIN — db2expln stmt
    explain_text = ""
    try:
        s_explain = ibm_db.prepare(
            conn,
            "EXPLAIN PLAN FOR SELECT id FROM bench_memories ORDER BY VECTOR_DISTANCE(embedding, VECTOR(?, 768, FLOAT32), EUCLIDEAN) FETCH APPROX FIRST 10 ROWS ONLY",
        )
        ibm_db.execute(s_explain, (json.dumps(queries[0]),))
        # Get plan text
        s2 = ibm_db.exec_immediate(
            conn,
            "SELECT OPERATOR_TYPE, TOTAL_COST FROM EXPLAIN_OPERATOR WHERE EXPLAIN_INSTANCE = (SELECT MAX(EXPLAIN_INSTANCE) FROM EXPLAIN_OPERATOR) ORDER BY OPERATOR_ID FETCH FIRST 20 ROWS ONLY",
        )
        if s2:
            r = ibm_db.fetch_assoc(s2)
            while r:
                explain_text += f"{r.get('OPERATOR_TYPE','?')}\t{r.get('TOTAL_COST','?')}\n"
                r = ibm_db.fetch_assoc(s2)
    except Exception as e:
        explain_text = f"explain failed: {e}"

    # Prepare once
    fetch_kw = "FETCH APPROX FIRST 10 ROWS ONLY" if indexed else "FETCH FIRST 10 ROWS ONLY"
    s_vec = ibm_db.prepare(
        conn,
        f"SELECT id FROM bench_memories ORDER BY VECTOR_DISTANCE(embedding, VECTOR(?, {EMBED_DIM}, FLOAT32), EUCLIDEAN) {fetch_kw}",
    )

    # Warmup
    for qv in queries[:WARMUP]:
        ibm_db.execute(s_vec, (json.dumps(qv),))
        while ibm_db.fetch_assoc(s_vec):
            pass

    # Single-point bench (DB2 EAP has no exposed search knob)
    lat, recalls = [], []
    for i, qv in enumerate(queries):
        t0 = time.perf_counter()
        ibm_db.execute(s_vec, (json.dumps(qv),))
        ret = []
        r = ibm_db.fetch_assoc(s_vec)
        while r:
            ret.append(r["ID"])
            r = ibm_db.fetch_assoc(s_vec)
        lat.append(time.perf_counter() - t0)
        if i < len(exact_topk):
            recalls.append(recall_at_k(ret, exact_topk[i]))

    results = {
        "engine": "db2-diskann",
        "n": len(rows),
        "ingest_rec_per_sec": round(len(rows) / ingest_s, 2),
        "ingest_total_sec": round(ingest_s, 2),
        "build_index_sec": round(idx_s, 2),
        "indexed": indexed,
        "explain_vector": explain_text[:2000],
        "sweep": [
            {
                "knob": "FETCH_APPROX",
                "latency": summ(lat),
                "recall_at_10_mean": round(statistics.mean(recalls), 4) if recalls else None,
                "recall_at_10_min": round(min(recalls), 4) if recalls else None if recalls else None,
            }
        ],
    }

    # fetch_by_id
    ids = [r["id"] for r in rows]
    s_fetch = ibm_db.prepare(conn, "SELECT id, content, category, tag FROM bench_memories WHERE id=?")
    fetch_lat = []
    for _ in range(N_QUERY):
        i = random.choice(ids)
        t0 = time.perf_counter()
        ibm_db.execute(s_fetch, (i,))
        ibm_db.fetch_assoc(s_fetch)
        fetch_lat.append(time.perf_counter() - t0)
    results["fetch_by_id"] = summ(fetch_lat)

    # filter_search
    s_filt = ibm_db.prepare(conn, "SELECT id FROM bench_memories WHERE category=? AND tag=? FETCH FIRST 10 ROWS ONLY")
    filt_lat = []
    for _ in range(N_QUERY):
        cat, tag = random.choice(CATS), random.choice(TAGS)
        t0 = time.perf_counter()
        ibm_db.execute(s_filt, (cat, tag))
        while ibm_db.fetch_assoc(s_filt):
            pass
        filt_lat.append(time.perf_counter() - t0)
    results["filter_search"] = summ(filt_lat)

    ibm_db.close(conn)
    return results


# ============== Oracle (scan SIMD; HNSW if vector_memory configured) ==============
def bench_oracle(dsn, rows, queries, exact_topk):
    import oracledb
    import re

    m = re.match(r"oracle://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)", dsn)
    conn = oracledb.connect(user=m.group(1), password=m.group(2), dsn=f"{m.group(3)}:{m.group(4)}/{m.group(5)}")
    cur = conn.cursor()
    print(f"[oracle] connected (n={len(rows)})")
    try:
        cur.execute("DROP TABLE bench_memories PURGE")
    except Exception:
        pass
    cur.execute(
        f"CREATE TABLE bench_memories(id VARCHAR2(64) PRIMARY KEY, content CLOB, category VARCHAR2(64), tag VARCHAR2(64), embedding VECTOR({EMBED_DIM}, FLOAT32))"
    )
    conn.commit()

    t0 = time.perf_counter()
    cur.executemany(
        "INSERT INTO bench_memories(id,content,category,tag,embedding) VALUES (:1,:2,:3,:4,TO_VECTOR(:5))",
        [(r["id"], r["content"], r["category"], r["tag"], json.dumps(r["embedding"])) for r in rows],
    )
    conn.commit()
    ingest_s = time.perf_counter() - t0
    print(f"[oracle] ingest {len(rows)} in {ingest_s:.2f}s = {len(rows)/ingest_s:.1f} rec/s")

    t0 = time.perf_counter()
    try:
        cur.execute("CREATE INDEX ix_bench_cat ON bench_memories(category)")
    except Exception:
        pass
    try:
        cur.execute("CREATE INDEX ix_bench_tag ON bench_memories(tag)")
    except Exception:
        pass
    indexed_hnsw = False
    try:
        cur.execute(
            "CREATE VECTOR INDEX ix_bench_emb ON bench_memories(embedding) ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE EUCLIDEAN PARAMETERS (TYPE HNSW, NEIGHBORS 32, EFCONSTRUCTION 200)"
        )
        indexed_hnsw = True
        print("[oracle] HNSW INMEMORY built")
    except Exception as e:
        print(f"[oracle] HNSW: {str(e)[:120]} — scan SIMD")
    try:
        cur.execute("BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, 'BENCH_MEMORIES'); END;")
    except Exception:
        pass
    idx_s = time.perf_counter() - t0

    # EXPLAIN
    explain_text = ""
    try:
        cur.execute(
            "EXPLAIN PLAN FOR SELECT id FROM bench_memories ORDER BY VECTOR_DISTANCE(embedding, TO_VECTOR(:1), EUCLIDEAN) FETCH FIRST 10 ROWS ONLY",
            [json.dumps(queries[0])],
        )
        cur.execute("SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY)")
        explain_text = "\n".join(r[0] for r in cur.fetchall())
    except Exception as e:
        explain_text = f"explain: {e}"

    # Warmup
    for qv in queries[:WARMUP]:
        cur.execute(
            "SELECT id FROM bench_memories ORDER BY VECTOR_DISTANCE(embedding, TO_VECTOR(:1), EUCLIDEAN) FETCH FIRST 10 ROWS ONLY",
            [json.dumps(qv)],
        )
        cur.fetchall()

    # Sweep — if HNSW built, sweep TARGET_ACCURACY
    sweep = []
    if indexed_hnsw:
        for ta in [80, 90, 95]:
            lat, recalls = [], []
            for i, qv in enumerate(queries):
                t0 = time.perf_counter()
                cur.execute(
                    f"SELECT id FROM bench_memories ORDER BY VECTOR_DISTANCE(embedding, TO_VECTOR(:1), EUCLIDEAN) FETCH APPROX FIRST 10 ROWS ONLY WITH TARGET ACCURACY {ta}",
                    [json.dumps(qv)],
                )
                ret = [r[0] for r in cur.fetchall()]
                lat.append(time.perf_counter() - t0)
                if i < len(exact_topk):
                    recalls.append(recall_at_k(ret, exact_topk[i]))
            sweep.append(
                {
                    "knob": f"TARGET_ACCURACY={ta}",
                    "latency": summ(lat),
                    "recall_at_10_mean": round(statistics.mean(recalls), 4) if recalls else None,
                    "recall_at_10_min": round(min(recalls), 4) if recalls else None,
                }
            )
    else:
        # Linear scan with SIMD
        lat, recalls = [], []
        for i, qv in enumerate(queries):
            t0 = time.perf_counter()
            cur.execute(
                "SELECT id FROM bench_memories ORDER BY VECTOR_DISTANCE(embedding, TO_VECTOR(:1), EUCLIDEAN) FETCH FIRST 10 ROWS ONLY",
                [json.dumps(qv)],
            )
            ret = [r[0] for r in cur.fetchall()]
            lat.append(time.perf_counter() - t0)
            if i < len(exact_topk):
                recalls.append(recall_at_k(ret, exact_topk[i]))
        sweep.append(
            {
                "knob": "scan_simd",
                "latency": summ(lat),
                "recall_at_10_mean": round(statistics.mean(recalls), 4) if recalls else None,
                "recall_at_10_min": round(min(recalls), 4) if recalls else None,
            }
        )

    results = {
        "engine": "oracle-23ai",
        "n": len(rows),
        "ingest_rec_per_sec": round(len(rows) / ingest_s, 2),
        "ingest_total_sec": round(ingest_s, 2),
        "build_index_sec": round(idx_s, 2),
        "indexed_hnsw": indexed_hnsw,
        "explain_vector": explain_text[:2000],
        "sweep": sweep,
    }

    # fetch_by_id
    ids = [r["id"] for r in rows]
    fetch_lat = []
    for _ in range(N_QUERY):
        i = random.choice(ids)
        t0 = time.perf_counter()
        cur.execute("SELECT id FROM bench_memories WHERE id=:1", [i])
        cur.fetchone()
        fetch_lat.append(time.perf_counter() - t0)
    results["fetch_by_id"] = summ(fetch_lat)

    # filter_search
    filt_lat = []
    for _ in range(N_QUERY):
        cat, tag = random.choice(CATS), random.choice(TAGS)
        t0 = time.perf_counter()
        cur.execute("SELECT id FROM bench_memories WHERE category=:1 AND tag=:2 FETCH FIRST 10 ROWS ONLY", [cat, tag])
        cur.fetchall()
        filt_lat.append(time.perf_counter() - t0)
    results["filter_search"] = summ(filt_lat)

    conn.close()
    return results


def main():
    print(f"[v4] N_SEED={N_SEED} N_QUERY={N_QUERY} WARMUP={WARMUP} EMBED={EMBED_DIM} K={K}")
    print(f"[v4] generating {N_SEED} clustered embeddings + {N_QUERY} queries...")
    rows = gen_rows(N_SEED)
    queries = gen_clustered(N_QUERY, EMBED_DIM, n_clusters=20)

    results = {
        "meta": {
            "version": "v4-defensible",
            "n_seed": N_SEED,
            "n_query": N_QUERY,
            "warmup": WARMUP,
            "embed_dim": EMBED_DIM,
            "k": K,
            "embeddings": "mixture-of-gaussians (20 clusters, noise=0.3)",
            "distance": "euclidean",
            "host": "CERBERUS",
            "container_shm": "8g equalized",
        }
    }

    pg_dsn = os.environ.get("PG_DSN", "postgresql://mnemos:mnemos_dev@127.0.0.1:5432/mnemos")
    db2_dsn = os.environ.get("DB2_DSN", "db2://db2inst1:mnemos_dev@127.0.0.1:50001/MNEMOS")
    oracle_dsn = os.environ.get("ORACLE_DSN", "oracle://MNEMOS:mnemos_dev@127.0.0.1:1522/ORCLPDB1")

    # Phase 1: PG bench with index — also compute exact baseline via PG with no index
    print("\n=== PG HNSW bench ===")
    try:
        results["pg"] = asyncio.run(bench_pg(pg_dsn, rows, queries, []))
    except Exception as e:
        results["pg_error"] = f"{type(e).__name__}: {e}"
        print(f"[pg] FAIL: {e}")
        return

    # Phase 1.5: compute exact top-K via PG (separate run, table already populated)
    print("\n=== exact top-K baseline (PG no-index) ===")
    try:
        exact_topk = asyncio.run(pg_exact_topk(pg_dsn, rows, queries))
        results["meta"]["recall_baseline"] = "pg-seqscan"
    except Exception as e:
        print(f"[exact] FAIL: {e} — recall will be N/A")
        exact_topk = []
        results["meta"]["recall_baseline"] = "unavailable"

    # Re-compute PG recall now that we have exact_topk
    if exact_topk and "pg" in results:
        # Re-run quick PG with exact_topk for recall measurement (sweep already done; just recall pass)
        # Actually the PG sweep above didn't have exact_topk so recall is 0. Re-run.
        print("\n=== PG sweep with recall ===")
        try:
            results["pg"] = asyncio.run(bench_pg(pg_dsn, rows, queries, exact_topk))
        except Exception as e:
            results["pg_error_2"] = f"{type(e).__name__}: {e}"

    # Phase 2: DB2
    print("\n=== DB2 DiskANN bench ===")
    try:
        results["db2"] = bench_db2(db2_dsn, rows, queries, exact_topk)
    except Exception as e:
        results["db2_error"] = f"{type(e).__name__}: {e}"
        print(f"[db2] FAIL: {e}")

    # Phase 3: Oracle
    print("\n=== Oracle bench ===")
    try:
        results["oracle"] = bench_oracle(oracle_dsn, rows, queries, exact_topk)
    except Exception as e:
        results["oracle_error"] = f"{type(e).__name__}: {e}"
        print(f"[oracle] FAIL: {e}")

    ts = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    out = Path.home() / "mnemos-bakeoff/docs/proof" / f"bench-v4-defensible-{N_SEED}-{ts}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(results, indent=2))
    print(f"\nartifact: {out}")


if __name__ == "__main__":
    main()
