"""DB-row to MPF-entry serializers."""

from __future__ import annotations

import json
from typing import Any, Dict

from .schemas import (
    MEMORY_PAYLOAD_VERSION,
    MPF_VERSION_PREFIX_V0_2,
    MPFRecord,
)
from .timestamps import _iso


# Mapping of MNEMOS source_provider / source_agent string fragments to
# PROV-DM activity-type discriminators per the MPF v0.2 spec. Order
# matters — first match wins. Used as the fallback heuristic when the
# row doesn't carry first-class provenance columns (federation_source,
# morpheus_run_id, provenance='morpheus_local').
_ACTIVITY_TYPE_HINTS = (
    ("morpheus", "distillation"),
    ("apollo", "distillation"),
    ("artemis", "distillation"),
    ("federation", "federation_pull"),
    ("graeae", "etl_job"),
    ("docling", "etl_job"),
    ("ingest", "etl_job"),
)


def _derive_prov_activity_type(row) -> str:
    """Derive a PROV activity-type discriminator from MNEMOS row context.

    Defaults to 'chat_session' which is the most common shape for
    MNEMOS-stored memories (operator-driven Claude/openclaw chat).
    """
    haystack = " ".join(
        str(row.get(field) or "")
        for field in ("source_provider", "source_agent", "source_session")
    ).lower()
    for hint, activity_type in _ACTIVITY_TYPE_HINTS:
        if hint in haystack:
            return activity_type
    return "chat_session"


def _record_provenance_v0_2(row) -> Dict[str, Any]:
    """Build the W3C PROV-DM provenance dict per MPF v0.2 spec.

    Required fields: wasAttributedTo (agent/user/system), wasGeneratedBy
    (activity), generatedAtTime (ISO datetime). Optional: wasInfluencedBy
    (memories or external URIs).

    The export query SELECTs provenance-bearing columns first-class:
        prov_kind        — postgres `provenance` column. 'morpheus_local'
                           for morpheus-synthesized memories, otherwise
                           NULL for chat/etl/etc.
        morpheus_run_id  — UUID of the morpheus run that produced this row
        source_memories  — text[] of memory IDs this row was distilled from
        federation_source— peer name when this row was pulled from a
                           federated peer

    Use those for high-fidelity PROV when present; fall back to the
    source_provider/agent heuristic otherwise.
    """
    owner_id = row.get("owner_id") or "default"
    if str(owner_id).lower() in {"default", "system", "mnemos"}:
        attributed_type = "system"
    else:
        attributed_type = "user"

    # 1) Federation: peer pull. Authoritatively a federation_pull
    #    activity attributed to the system (federation worker), not the
    #    original owner.
    federation_source = row.get("federation_source")
    if federation_source:
        prov: Dict[str, Any] = {
            "wasAttributedTo": {"type": "system", "id": f"federation:{federation_source}"},
            "wasGeneratedBy": {
                "type": "federation_pull",
                "id": f"federation:{federation_source}",
            },
            "generatedAtTime": (
                _iso(row.get("created")) or _iso(row.get("updated")) or ""
            ),
        }
        return prov

    # 2) Morpheus distillation: prov_kind/provenance must be set to
    #    'morpheus_local' (the deterministic signal that this row was
    #    GENERATED by Morpheus). morpheus_run_id alone is NOT sufficient
    #    — `phase_consolidate` updates EXISTING user-authored memories
    #    with the run_id to track which run touched them, but leaves
    #    provenance non-morpheus_local and source_memories unset. Those
    #    rows must keep their original user attribution, not become
    #    "synthesized by mnemos:morpheus".
    morpheus_run_id = row.get("morpheus_run_id")
    prov_kind = row.get("prov_kind") or row.get("provenance")
    is_morpheus = isinstance(prov_kind, str) and "morpheus" in prov_kind.lower()
    if is_morpheus:
        activity_id = morpheus_run_id or "morpheus_local"
        # Cross-backend column shape:
        # - Postgres: `source_memories` (text[])
        # - SQLite:   `source_memory_ids` (TEXT, JSON-encoded array)
        # Read both keys with explicit fallback so neither backend's
        # naming silently drops the lineage.
        source_memories = (
            row.get("source_memories")
            or row.get("source_memory_ids")
            or []
        )
        if isinstance(source_memories, str):
            try:
                parsed = json.loads(source_memories)
                if isinstance(parsed, list):
                    source_memories = parsed
                else:
                    source_memories = []
            except (json.JSONDecodeError, TypeError):
                source_memories = []
        prov = {
            "wasAttributedTo": {"type": "system", "id": "mnemos:morpheus"},
            "wasGeneratedBy": {
                "type": "distillation",
                "id": f"morpheus:{activity_id}",
            },
            "generatedAtTime": (
                _iso(row.get("created")) or _iso(row.get("updated")) or ""
            ),
        }
        if source_memories:
            prov["wasInfluencedBy"] = [
                {"type": "memory", "id": str(mid)} for mid in source_memories
            ]
        return prov

    # 3) Default heuristic path (chat / graeae / etl / etc).
    activity_id = (
        row.get("source_session")
        or row.get("source_agent")
        or row.get("source_provider")
        or f"mem:{row['id']}"
    )

    prov = {
        "wasAttributedTo": {"type": attributed_type, "id": owner_id},
        "wasGeneratedBy": {
            "type": _derive_prov_activity_type(row),
            "id": str(activity_id),
        },
        "generatedAtTime": _iso(row.get("created")) or _iso(row.get("updated")) or "",
    }
    return prov


def _memory_to_record(row, *, mpf_version: str = "0.1.1") -> MPFRecord:
    """Serialize a memories row to an MPF record.

    ``mpf_version`` selects the emission shape. v0.1.x: legacy payload
    only, no record-level provenance / bi-temporal fields. v0.2.x: adds
    ``provenance`` (required for kind=memory), ``transaction_time``
    (defaults to created), and optional ``valid_time_start`` /
    ``valid_time_end`` (sourced from metadata.valid_time.* if present).
    """
    metadata = row.get("metadata") or {}
    if isinstance(metadata, str):
        try:
            metadata = json.loads(metadata)
        except Exception:
            metadata = {"_raw": metadata}

    payload: Dict[str, Any] = {
        "content": row.get("content"),
        "category": row.get("category"),
        "subcategory": row.get("subcategory"),
        "created": _iso(row.get("created")),
        "updated": _iso(row.get("updated")),
        "owner_id": row.get("owner_id"),
        "namespace": row.get("namespace"),
        "permission_mode": row.get("permission_mode"),
        "quality_rating": row.get("quality_rating"),
        "source_model": row.get("source_model"),
        "source_provider": row.get("source_provider"),
        "source_session": row.get("source_session"),
        "source_agent": row.get("source_agent"),
        "metadata": metadata,
    }
    payload = {k: v for k, v in payload.items() if v is not None}

    record_kwargs: Dict[str, Any] = dict(
        id=row["id"],
        kind="memory",
        payload_version=MEMORY_PAYLOAD_VERSION,
        payload=payload,
    )

    # v0.2 record-level fields. Operators can override valid_time_* via
    # metadata.valid_time.{start,end}; otherwise defaults to created /
    # null per the spec's "MNEMOS importers default valid_time_start to
    # transaction_time" guidance.
    if mpf_version.startswith(MPF_VERSION_PREFIX_V0_2):
        record_kwargs["provenance"] = _record_provenance_v0_2(row)
        record_kwargs["transaction_time"] = _iso(row.get("created"))
        valid_time_meta = (
            metadata.get("valid_time") if isinstance(metadata, dict) else None
        )
        if isinstance(valid_time_meta, dict):
            vt_start = _iso(valid_time_meta.get("start"))
            vt_end = _iso(valid_time_meta.get("end"))
            record_kwargs["valid_time_start"] = vt_start or _iso(row.get("created"))
            record_kwargs["valid_time_end"] = vt_end  # may be None
        else:
            record_kwargs["valid_time_start"] = _iso(row.get("created"))
            # valid_time_end stays None (open-ended/current)

    return MPFRecord(**record_kwargs)


def _normalize_confidence_for_mpf(raw: Any) -> tuple[Any, Any]:
    """Clamp `confidence` to [0.0, 1.0] for MPF v0.2 schema conformance.

    Returns (normalized, original_if_clamped_else_None). DB-side rows can
    legitimately carry out-of-range values (e.g. accumulated weight
    rather than a probability) — preserve the original in metadata so
    importers that round-trip back can recover. NaN/Infinity are rejected:
    JSON has no representation for them and FastAPI/Starlette would 500
    on the response. The original is stringified for stash so it stays
    JSON-safe.
    """
    import math

    if raw is None:
        return (None, None)
    try:
        f = float(raw)
    except (TypeError, ValueError):
        return (None, raw)  # drop the field, stash the raw
    if not math.isfinite(f):
        # NaN / +Inf / -Inf: stringify so the metadata stash is JSON-safe.
        return (None, str(raw) if not isinstance(raw, str) else raw)
    if 0.0 <= f <= 1.0:
        return (f, None)
    clamped = 0.0 if f < 0.0 else 1.0
    return (clamped, raw)


def _kg_triple_to_entry(row, *, mpf_version: str = "0.1.1") -> Dict[str, Any]:
    """Serialize a kg_triples row for MPF.

    v0.1.x emits raw DB values verbatim (backward-compat). v0.2.x clamps
    `confidence` to [0, 1] and stashes any clamped raw value in
    metadata._mnemos_raw_confidence for round-trip fidelity.
    """
    metadata = row.get("metadata") or {}
    if isinstance(metadata, str):
        try:
            metadata = json.loads(metadata)
        except Exception:
            metadata = {"_raw": metadata}

    is_v0_2 = mpf_version.startswith(MPF_VERSION_PREFIX_V0_2)
    if is_v0_2:
        norm_conf, raw_conf = _normalize_confidence_for_mpf(row.get("confidence"))
        if raw_conf is not None and (not isinstance(metadata, dict) or
                                     metadata.get("_mnemos_raw_confidence") != raw_conf):
            if not isinstance(metadata, dict):
                metadata = {}
            metadata = {**metadata, "_mnemos_raw_confidence": raw_conf}
        confidence_value = norm_conf
    else:
        confidence_value = row.get("confidence")

    entry: Dict[str, Any] = {
        "id": row["id"],
        "predicate": row["predicate"],
        "subject_literal": row.get("subject"),
        "object_literal": row.get("object"),
        "subject_type": row.get("subject_type"),
        "object_type": row.get("object_type"),
        "memory_id": row.get("memory_id"),
        "confidence": confidence_value,
        "valid_from": _iso(row.get("valid_from")),
        "valid_until": _iso(row.get("valid_until")),
        "created": _iso(row.get("created")),
        "owner_id": row.get("owner_id"),
        "namespace": row.get("namespace"),
    }
    if metadata:
        entry["metadata"] = metadata
    return {k: v for k, v in entry.items() if v is not None}


_MPF_V0_2_CHANGE_TYPES = frozenset(
    {"create", "update", "delete", "revert", "merge", "branch"}
)


def _normalize_change_type_for_mpf(raw: Any) -> Any:
    """Map MNEMOS-internal change_type values to the MPF v0.2 spec set.

    The v0.2 spec (mnemos-os/mpf/blob/master/schema/mpf-v0.2.json) limits
    memory_versions[].change_type to {create, update, delete, revert,
    merge, branch}. MNEMOS's internal compression DAG also uses 'compress',
    which would fail validation. Normalize unrecognized values to 'update'
    (the closest semantic — a row mutation that produced a new version)
    so v0.2 envelopes stay schema-conformant. Capture the raw value in
    metadata if needed for future round-trip fidelity.
    """
    if raw is None:
        return None
    if raw in _MPF_V0_2_CHANGE_TYPES:
        return raw
    return "update"


def _memory_version_to_entry(row, *, mpf_version: str = "0.1.1") -> Dict[str, Any]:
    """Serialize a memory_versions row for MPF.

    v0.1.x emits change_type verbatim (backward-compat — the v0.1 schema
    didn't restrict the value set). v0.2.x normalizes unrecognized
    values to 'update' and stashes the original in
    metadata._mnemos_change_type for round-trip fidelity.
    """
    metadata = row.get("metadata") or {}
    if isinstance(metadata, str):
        try:
            metadata = json.loads(metadata)
        except Exception:
            metadata = {"_raw": metadata}
    merge_parents = row.get("merge_parents") or None
    if merge_parents is not None:
        merge_parents = [str(p) for p in merge_parents]
    parent_version_id = row.get("parent_version_id")
    if parent_version_id is not None:
        parent_version_id = str(parent_version_id)
    raw_change_type = row.get("change_type")
    is_v0_2 = mpf_version.startswith(MPF_VERSION_PREFIX_V0_2)
    if is_v0_2:
        change_type_out = _normalize_change_type_for_mpf(raw_change_type)
        if (
            raw_change_type is not None
            and raw_change_type != change_type_out
        ):
            if not isinstance(metadata, dict):
                metadata = {}
            metadata = {**metadata, "_mnemos_change_type": raw_change_type}
    else:
        change_type_out = raw_change_type
    entry: Dict[str, Any] = {
        "id": str(row["id"]),
        "record_id": row["memory_id"],
        "version_num": row["version_num"],
        "commit_hash": row.get("commit_hash"),
        "branch": row.get("branch"),
        "parent_version_id": parent_version_id,
        "merge_parents": merge_parents,
        "content": row["content"],
        "category": row.get("category"),
        "subcategory": row.get("subcategory"),
        "metadata": metadata or None,
        "verbatim_content": row.get("verbatim_content"),
        "owner_id": row.get("owner_id"),
        "namespace": row.get("namespace"),
        "permission_mode": row.get("permission_mode"),
        "source_model": row.get("source_model"),
        "source_provider": row.get("source_provider"),
        "source_session": row.get("source_session"),
        "source_agent": row.get("source_agent"),
        "snapshot_at": _iso(row.get("snapshot_at")),
        "snapshot_by": row.get("snapshot_by"),
        "change_type": change_type_out,
    }
    return {k: v for k, v in entry.items() if v is not None}


def _clamp_non_negative_int(raw: Any) -> Any:
    """Clamp an int-typed field to >= 0 for MPF v0.2 schema conformance.

    The v0.2 spec requires compressed_tokens >= 0; legacy DB rows can
    carry -1 as a sentinel for "unknown" or "not yet measured". Map
    those to None so the field is omitted from the envelope rather than
    failing schema validation. Non-numeric values become None too.
    """
    if raw is None:
        return None
    try:
        n = int(raw)
    except (TypeError, ValueError):
        return None
    return n if n >= 0 else None


def _deletion_log_to_entry(row, *, mpf_version: str = "0.1.1") -> Dict[str, Any]:
    """Serialize a deletion_log row for the MPF v0.2 deletion_log sidecar.

    Spec required fields (per mnemos-os/mpf v0.2.0 schema): id, record_id,
    deleted_at. Optional: deleted_by, reason, tombstone_hash, provenance.

    Mapping from MNEMOS deletion_log table:
        id          -> id (UUID stringified)
        memory_id   -> record_id (the deleted memory's id)
        executed_at -> deleted_at (when MNEMOS recorded the deletion)
        requested_by-> deleted_by (the user/agent that asked)
        reason      -> reason (verbatim)
        content_hash-> tombstone_hash (final-state hash before tombstone)

    Extra MNEMOS-specific fields (request_kind, requested_at, source[])
    go in metadata for round-trip fidelity. v0.1 emission is a no-op
    since the v0.1 envelope has no deletion_log sidecar.
    """
    if not mpf_version.startswith(MPF_VERSION_PREFIX_V0_2):
        return {}

    deleted_at = _iso(row.get("executed_at"))
    if not deleted_at:
        # Required field — fall back to requested_at if executed_at is
        # somehow missing. If both are missing, skip the row entirely
        # (caller should drop the entry).
        deleted_at = _iso(row.get("requested_at"))
    entry: Dict[str, Any] = {
        "id": str(row["id"]),
        "record_id": row["memory_id"],
        "deleted_at": deleted_at,
        "deleted_by": row.get("requested_by"),
        "reason": row.get("reason"),
        "tombstone_hash": row.get("content_hash"),
    }
    # Extra context for round-trip / audit replay.
    extra_metadata: Dict[str, Any] = {}
    if row.get("request_kind"):
        extra_metadata["_mnemos_request_kind"] = row["request_kind"]
    if row.get("requested_at"):
        extra_metadata["_mnemos_requested_at"] = _iso(row.get("requested_at"))
    if row.get("source"):
        extra_metadata["_mnemos_source"] = list(row["source"])
    if extra_metadata:
        entry["metadata"] = extra_metadata
    return {k: v for k, v in entry.items() if v is not None}


def _compression_variant_to_entry(row, *, mpf_version: str = "0.1.1") -> Dict[str, Any]:
    """Serialize a memory_compressed_variants row for MPF.

    v0.1.x emits compressed_tokens verbatim (backward-compat — legacy
    DBs use -1 as a "not measured" sentinel). v0.2.x clamps to >= 0 per
    the v0.2 spec.
    """
    winner_id = row.get("winner_candidate_id")
    if winner_id is not None:
        winner_id = str(winner_id)
    is_v0_2 = mpf_version.startswith(MPF_VERSION_PREFIX_V0_2)
    if is_v0_2:
        compressed_tokens_out = _clamp_non_negative_int(row.get("compressed_tokens"))
    else:
        compressed_tokens_out = row.get("compressed_tokens")
    entry: Dict[str, Any] = {
        "record_id": row["memory_id"],
        "engine_id": row["engine_id"],
        "engine_version": row.get("engine_version"),
        "compressed_content": row.get("compressed_content"),
        "compressed_tokens": compressed_tokens_out,
        "compression_ratio": row.get("compression_ratio"),
        "quality_score": row.get("quality_score"),
        "composite_score": row.get("composite_score"),
        "scoring_profile": row.get("scoring_profile"),
        "judge_model": row.get("judge_model"),
        "selected_at": _iso(row.get("selected_at")),
        "winner_contest_id": winner_id,
        "owner_id": row.get("owner_id"),
    }
    return {k: v for k, v in entry.items() if v is not None}
